### ISSUE TITLE
编译后在左侧菜单中不显示"屏幕"菜单栏，直接访问链接也无法访问

### ISSUE THREAD

**Issue by ningnao** [Hill-98/luci-app-k3screenctrl#5]
固件是lean的openwrt(lede)的最新版本

![image](https://user-images.githubusercontent.com/118373565/206481146-3ae1a3d5-ad85-496f-8577-ea8fcf35e62d.png)

![image](https://user-images.githubusercontent.com/118373565/206481328-6b0edca2-a78c-448d-9597-b5f60facee45.png)

**Comment by Hill-98** [comment]
尝试安装`luci-compat`软件包

**Comment by ningnao** [comment]
已经安装了这个软件包
![image](https://user-images.githubusercontent.com/118373565/206485101-ec582bf9-656d-41d9-b8b3-ded53f74e0bc.png)

**Comment by Hill-98** [comment]
你能提供一下这个固件是基于那个OpenWrt发布版本吗？

**Comment by ningnao** [comment]
这个我并不了解... 有主题作者提过是基于18.06版本，我不确定..
不过经过测试在openwrt官方的最新22.03.2版本可以正常显示

**Comment by Hill-98** [comment]
有时间我测试一下

**Comment by ningnao** [comment]
十分感谢！！！！

**Comment by ningnao** [comment]
找到问题所在了，lean的固件package里有一个同名的k3screenctrl，错误的覆盖了这个包依赖的[openwrt-k3screenctrl](https://github.com/Hill-98/openwrt-k3screenctrl)
